alter PROCEDURE USP_AGREGAPEDIDO
@IDPED INT,
@IDCLI VARCHAR(5),
@IDEMP INT,
@FECPED DATETIME,
@IDPROD INT,
@PRE DECIMAL,
@CANT INT,
@SALIDA varchar(100) output
AS
declare @exis as decimal(10,2)
	
	select @exis= UNIdadesENEXISTENCIA from COMPRA.productos
	where  IDPRODUCTO = @IDPROD
	iF ( @CANT <= @exis )
	BEGIN
		UPDATE COMPRA.PRODUCTOS SET UNIdadesENEXISTENCIA -=@CANT  
		WHERE IDPRODUCTO = @IDPROD
		
		INSERT INTO
		VENTA.PEDIDOSCABE(IDPEDIDO, IDCLIENTE, IDEMPLEADO, FECHAPEDIDO,destinatario,dirdestinatario,fechaentrega ,fechaenvio,enviopedido     )
		VALUES(@IDPED, @IDCLI, @IDEMP, @FECPED,'WEFWE','DIRDES','','','')

		INSERT INTO dbo.PEDIDOSDETA(IDPEDIDO, IDPRODUCTO, PRECIOUNIDAD, CANTIDAD, DESCUENTO)
		VALUES(@IDPED, @IDPROD, @PRE, @CANT, 0)
		
	END
    ELSE
    BEGIN
		raiserror('No Hay Existencia',16,1)
	END	
GO

DECLARE @SALIDA VARCHAR(100)
exec USP_AGREGAPEDIDO
@IDPED = 251,
@IDCLI ='NCBCK',
@IDEMP = 1,
@FECPED ='01-01-2014',
@IDPROD = 1,
@PRE = 10.2,
@CANT= 1,
go

select * from VENTA.pedidoscabe
select * from dbo.PEDIDOSDETA 

DECLARE @SALIDA VARCHAR(100)
exec USP_AGREGAPEDIDO
@IDPED = 2511,
@IDCLI ='NCBCK',
@IDEMP = 1,
@FECPED ='01-01-2014',
@IDPROD = 15,
@PRE = 10.2,
@CANT= 1
go

select * from VENTA.pedidoscabe
select * from dbo.PEDIDOSDETA 
