alter PROCEDURE USP_PRODUCTO_CLIENTE
@IDCLI VARCHAR(5),
@AÑO INT = 0, 
@IDPRODUCTO_P INT OUTPUT,
@NOMPRO_P VARCHAR(35) OUTPUT
AS
if @AÑO = 0 SET @AÑO= YEAR(GETDATE() )
SELECT TOP 1 @IDPRODUCTO_P= pro.idproducto ,
    @NOMPRO_P= pro.nombreproducto ,sum(CANTIDAD) 
FROM COMPRA.productos pro
JOIN dbo.PEDIDOSDETA pedd ON pro.idproducto = pedd.idproducto
JOIN VENTA.pedidoscabe pedc ON pedd.idpedido = pedc.idpedido
WHERE pedc.idcliente = @IDCLI  AND
YEAR(FECHAPEDIDO) = @AÑO
group by pro.idproducto ,pro.nombreproducto
ORDER BY sum(CANTIDAD) DESC
GO
-- Aqui no enviamos Año. Cogerá AÑO actual
DECLARE @IDPRODUC INT,@NOMPR VARCHAR(35)
EXEC USP_PRODUCTO_CLIENTE 
@IDCLI='NCBCK',
@IDPRODUCTO_P=@IDPRODUC OUTPUT,
@NOMPRO_P=@NOMPR OUTPUT
-- Aqui  enviamos Año. NO Cogerá AÑO actual
SELECT  'iD PRODUCTO:' + STR(@IDPRODUC) , 
'NOMBRE:' + @NOMPR  
GO
DECLARE @IDPRODUC INT,@NOMPR VARCHAR(35)
EXEC USP_PRODUCTO_CLIENTE 
@IDCLI='NCBCK',
@AÑO=2012,
@IDPRODUCTO_P=@IDPRODUC OUTPUT,
@NOMPRO_P=@NOMPR OUTPUT
SELECT  'iD PRODUCTO:' + STR(@IDPRODUC) , 'NOMBRE:' + @NOMPR
GO
-- La forma mas sencilla respetando orden
DECLARE @IDPRODUC INT,@NOMPR VARCHAR(35)
EXEC USP_PRODUCTO_CLIENTE 'NCBCK',2017,
@IDPRODUC OUTPUT,
@NOMPR OUTPUT
SELECT  'iD PRODUCTO:' + STR(@IDPRODUC) , 'NOMBRE:' + @NOMPR
GO





