SELECT  C.IDPAIS , SUM(PRECIOUNIDAD*CANTIDAD)  
FROM dbo.PEDIDOSDETA PD JOIN VENTA.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
JOIN VENTA.clientes C ON C.IDCLIENTE = PC.IDCLIENTE
WHERE YEAR(FECHAPEDIDO)=2013
GROUP BY C.IDPAIS
ORDER BY 2 DESC