USE negocios2011
GO
create PROCEDURE USP_PRODVENTAPAISES
@PROD INT,
@ANIO INT,
@NUMPAISES INT OUTPUT
AS

SELECT @NUMPAISES = COUNT(*)
FROM VENTA.clientes c 
JOIN VENTA.pedidoscabe vp ON c.idcliente = vp.idcliente
JOIN dbo.PEDIDOSDETA pd ON vp.idpedido = pd.idpedido
WHERE pd.idproducto = @PROD
AND YEAR(vp.fechapedido) = @ANIO
GROUP BY C.idpais
GO

DECLARE @NUMPAISES INT
EXEC USP_PRODVENTAPAISES
@PROD = 89,
@ANIO = 2012,
@NUMPAISES = @NUMPAISES OUTPUT


SELECT  @NUMPAISES AS Cantidad_Paises

