use negocios2011 
-- select para probar
SELECT pc.idcliente , SUM(PD.PRECIOUNIDAD*PD.CANTIDAD) 
FROM dbo.PEDIDOSDETA PD JOIN VENTA.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
group by pc.idcliente 
--
--ALTER TABLE VENTA.clientes
 --ADD descuento DECIMAL(5,2) NULL;
GO	
DECLARE @COCLI VARCHAR(5), @TOTAL AS DECIMAL(10,2)
DECLARE @dto AS DECIMAL(5,2)

SET @COCLI = 'HGWIK'
SELECT @TOTAL = SUM(PD.PRECIOUNIDAD*PD.CANTIDAD) 
FROM dbo.PEDIDOSDETA PD JOIN VENTA.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
WHERE PC.IDCLIENTE= @COCLI
IF @TOTAL > 1000.00
	SET @DTO=10
	ELSE IF @TOTAL > 100
	SET @DTO=5
	ELSE
	SET @DTO=0
UPDATE VENTA.clientes 
SET Descuento = @DTO 
WHERE IDCLIENTE = @COCLI
PRINT 'Descuento ' + STR(@DTO) +'%'
GO
