USE [negocios2011]
GO
ALTER FUNCTION [dbo].PAISMASVENTA(@AÑO INT) 
RETURNS CHAR(3)
BEGIN
DECLARE @TOTAL AS DECIMAL(10,2),@PAIS VARCHAR(3)
SELECT TOP 1 @PAIS = C.IDPAIS ,@TOTAL = SUM(PRECIOUNIDAD*CANTIDAD) 
FROM dbo.PEDIDOSDETA PD JOIN VENTA.PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
JOIN VENTA.clientes C ON C.IDCLIENTE = PC.IDCLIENTE
WHERE YEAR(FECHAPEDIDO)=@AÑO 
GROUP BY C.IDPAIS
ORDER BY 1 desc
RETURN @PAIS
END
GO
SELECT DBO.PAISMASVENTA(2014)