create PROCEDURE USP_EMPLEDO_CARGO
@CARGO INT,
@EMPLE AS INT OUTPUT,
@TOTAL AS DECIMAL(10,2) OUTPUT
AS
SELECT TOP 1 @EMPLE = EM.idempleado,@TOTAL = EM.SALARIO
FROM rrhh.empleados EM 
WHERE EM.idcargo  = @CARGO
ORDER BY EM.Salario DESC
GO

DECLARE
@EMPLE AS INT ,
@TOTAL AS DECIMAL(10,2) 
 EXEC USP_EMPLEDO_CARGO
 @CARGO =49,
@EMPLE=@EMPLE OUTPUT,
@TOTAL=@TOTAL OUTPUT
-- o
 EXEC USP_EMPLEDO_CARGO 49,@EMPLE OUTPUT,
		@TOTAL OUTPUT
 
SELECT  'iD empleado:' + STR(@EMPLE) , 'Salario:' + STR(@TOTAL)
GO
