USE negocios2011
GO

create PROCEDURE USP_PRODVENTAPAISES
@PROD INT,
@ANIO INT,
@NUMPAISES INT OUTPUT

AS

SELECT @NUMPAISES = COUNT(DISTINCT C.idpais)
FROM VENTA.clientes c 
JOIN VENTA.pedidoscabe vp ON c.idcliente = vp.idcliente
JOIN dbo.PEDIDOSDETA pd ON vp.idpedido = pd.idpedido
WHERE pd.idproducto = @PROD
AND YEAR(vp.fechapedido) = @ANIO
GO

DECLARE @NUMPAISES INT
EXEC USP_PRODVENTAPAISES 89,2012,@NUMPAISES OUTPUT


DECLARE @NUMPAISES INT
EXEC USP_PRODVENTAPAISES
@NUMPAISES = @NUMPAISES OUTPUT,
@ANIO = 2012,
@PROD = 89


SELECT  @NUMPAISES AS Cantidad_Paises

