-- DECLARO VARIABLES DE TRABAJO
DECLARE @Y INT, @Y1 INT, @PEDIDO INT, @MONTO DECIMAL, @TOTAL
DECIMAL
SET @TOTAL=0
-- DECLARO EL CURSOR
DECLARE MI_CURSOR CURSOR FOR
SELECT YEAR(FECHAPEDIDO),PC.IDPEDIDO,SUM(PRECIOUNIDAD*CANTIDAD)
FROM VENTAS.PEDIDOSCABE PC
JOIN VENTAS.PEDIDOSDETA D ON PC.IDPEDIDO=D.IDPEDIDO
GROUP BY YEAR(FECHAPEDIDO), PC.IDPEDIDO
ORDER BY 1
OPEN MI_CURSOR -- ABRIR EL CURSOR
-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO
-- MIENTRAS PUEDA LEER EL REGISTRO
WHILE @@FETCH_STATUS=0
BEGIN	
	SET @Y1 = @Y -- Guardo el año 
  	PRINT 'AÑO:' + CAST(@Y1 AS VARCHAR)-- IMPRIMIR EL aÑO
	SET @TOTAL=0 -- Total del año a 0
	-- Mientras no cambie el año
	WHILE @@FETCH_STATUS=0 and  @Y = @Y1
	BEGIN
		SET @TOTAL += @MONTO --  ACUMULAR EL TOTAL año 
		-- IMPRIMIR EL REGISTRO
		PRINT CAST(@PEDIDO AS VARCHAR) + SPACE(5)+STR(@MONTO)
		-- LEER EL REGISTRO SIGUIENTE
		FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO
	END
--fin de año . Ha cambiado . Imprimo totales
	PRINT 'IMPORTE EN:' + CAST(@Y1 AS VARCHAR) +
		SPACE(2)+ 'ES ' +CAST(@TOTAL AS VARCHAR)
END -- fIN DE FICHERO O VUELVE A PRINCIPIO DE AÑO 

CLOSE MI_CURSOR -- CERRAR

DEALLOCATE MI_CURSOR; -- LIBERAR



