-- DECLARO VARIABLES DE TRABAJO
DECLARE @CLIENTE VARCHAR (30),@CLIENTEENCURSO VARCHAR (30), @ARTICULO VARCHAR (30), @ARTICULOENCURSO VARCHAR(30), @PEDIDO INT, @IMPORTEPEDIDO MONEY, @IMPORTEPRODUCTO MONEY, @IMPORTECLIENTE MONEY, @IMPORTETOTAL MONEY
PRINT  'INFORME DE PEDIDOS/PRODUCTO POR CLIENTE: (Ejer6)'
PRINT ''
-- DECLARO EL CURSOR
DECLARE MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE CURSOR FOR
SELECT C.nomcliente, P.nombreproducto, PC.idpedido, PD.cantidad*PD.preciounidad 
FROM venta.clientes c 
INNER JOIN venta.pedidoscabe PC ON C.idcliente=PC.idcliente
INNER JOIN  PEDIDOSDETA PD ON PC.idpedido=PD.idpedido 
INNER JOIN COMPRAS .productos P ON PD.idproducto=P.idproducto
ORDER BY  C.nomcliente, P.nombreproducto,PC.idpedido
-- ABRIR EL CURSOR
OPEN MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE
-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE INTO @CLIENTE, @ARTICULO, @PEDIDO, @IMPORTEPEDIDO
--EMPIEZO EL BUCLE PARA RECORRER LOS VALORES DE EMPLEADO
	SET @IMPORTETOTAL=0
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @CLIENTEENCURSO=@CLIENTE
		PRINT 'CLIENTE: ' + @CLIENTEENCURSO
		print ''
		PRINT 'ARTICULO' + CHAR(9) + 'PEDIDO' + CHAR(9) + 'IMPORTE'
		SET @IMPORTECLIENTE=0
		WHILE @CLIENTEENCURSO=@CLIENTE AND @@FETCH_STATUS=0
		BEGIN
			SET @ARTICULOENCURSO=@ARTICULO
			SET @IMPORTEPRODUCTO=0
			WHILE @ARTICULOENCURSO=@ARTICULO
				AND @CLIENTEENCURSO=@CLIENTE 
					AND @@FETCH_STATUS=0
			BEGIN
				PRINT CAST(@ARTICULO AS VARCHAR) + CHAR(9)+ CHAR(9) + CAST(@PEDIDO AS VARCHAR)+ CHAR(9) + CHAR(9) + CAST(@IMPORTEPEDIDO AS VARCHAR)
				SET @IMPORTEPRODUCTO+=@IMPORTEPEDIDO
				FETCH MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE INTO @CLIENTE, @ARTICULO, @PEDIDO, @IMPORTEPEDIDO
			END
			--Fin de producto
			PRINT ''
			PRINT 'TOTAL PRODUCTO ' + CAST(@ARTICULOENCURSO AS VARCHAR) + CHAR(9) + CAST(@IMPORTEPRODUCTO AS VARCHAR)
			PRINT ''
			SET @IMPORTECLIENTE+=@IMPORTEPRODUCTO
		END	
	--Fin de Cliente	
	PRINT ''
	PRINT 'IMPORTE CLIENTE ' + CAST(@CLIENTEENCURSO AS VARCHAR) + CHAR(9) + CAST(@IMPORTECLIENTE AS VARCHAR) 
	PRINT ''
	SET @IMPORTETOTAL+=@IMPORTECLIENTE
	
END
--Fin de 
PRINT 'IMPORTE TOTAL CLIENTE PRODUCTO PEDIDO: ' + CAST(@IMPORTETOTAL AS VARCHAR)
--CERRAR CURSOR
CLOSE MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE
-- LIBERAR
DEALLOCATE MI_CURSOR_CLIENTE_PRODUCTO_PEDIDO_IMPORTE