create PROCEDURE USP_REPORTEPEDIDOSXAÑOXEMPLEADO 
@EMP INT=1 
AS 
-- DECLARACIÓN DE VARIABLES DE TRABAJO 
DECLARE @Y INT, @YANT INT, @PEDIDO INT, @MONTO DECIMAL, @TOTAL DECIMAL 
SET @TOTAL=0 
-- DECLARACIÓN DEL CURSOR 
DECLARE MI_CURSOR CURSOR FOR
SELECT YEAR(FECHAPEDIDO) AS 'AÑO',
PC.IDPEDIDO,
SUM(PRECIOUNIDAD*CANTIDAD) AS MONTO 
FROM ventas.PEDIDOSCABE PC
JOIN ventas.PEDIDOSDETA PD
ON PC.IDPEDIDO=PD.IDPEDIDO 
WHERE IDEMPLEADO = @EMP 
GROUP BY YEAR(FECHAPEDIDO), PC.IDPEDIDO 
ORDER BY 1 
-- APERTURA DEL CURSOR 
OPEN MI_CURSOR 
-- LECTURA DEL PRIMER REGISTRO 
FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO 
WHILE @@FETCH_STATUS=0 
	BEGIN 
	---empieza un año
	-- Guardamos el año que tenemos
	SET @YANT = @Y 
	-- IMPRIMIR EL PRIMER AÑO 
	PRINT 'AÑO:' + CAST(@Y AS VARCHAR) 
	-- RECORRER EL CURSOS MIENTRAS HAYAN REGISTROS 
	WHILE(@Y = @YANT and @@FETCH_STATUS=0 )
	BEGIN 
		-- ACUMULAR 
		SET @TOTAL += @MONTO 
		-- IMPRIMIR EL REGISTRO 
		PRINT CAST(@PEDIDO AS VARCHAR) + SPACE(5)+ CAST(@MONTO AS VARCHAR)
		-- LECTURA DEL SIGUIENTE REGISTRO 
		FETCH MI_CURSOR INTO @Y, @PEDIDO, @MONTO 
	END 
	---Termina el año
	PRINT 'AÑO:' + CAST(@Yant AS VARCHAR) + SPACE(2)+ 'IMPORTE: ' + CAST(@TOTAL AS VARCHAR)
--- Aqui termina el fichero
END 
-- CERRAR EL CURSOR 
CLOSE MI_CURSOR 
-- LIBERAR EL RECURSO 
DEALLOCATE MI_CURSOR; 
GO
USP_REPORTEPEDIDOSXAÑOXEMPLEADO 2
GO