-- DECLARO VARIABLES DE TRABAJO
DECLARE @Y INT, @Y1 INT, @EMPLE INT, @NOMEMPLE VARCHAR (20),
@IMPORTE DECIMAL, @TOTAL_año DECIMAL,@TOTAL_final DECIMAL
-- DECLARO EL CURSOR
DECLARE MI_CURSOR_EMPLE CURSOR FOR
SELECT YEAR(FECHAPEDIDO),C.idempleado,e.nomempleado,SUM(PRECIOUNIDAD*CANTIDAD)
FROM venta.PEDIDOSCABE C
JOIN  PEDIDOSDETA D ON C.IDPEDIDO=D.IDPEDIDO
JOIN rrhh.empleados e ON C.idempleado=e.idempleado
GROUP BY YEAR(FECHAPEDIDO), C.idempleado, e.nomempleado
ORDER BY 1,2
-- ABRIR EL CURSOR
OPEN MI_CURSOR_EMPLE
--TOTALES FINALES 
SET @TOTAL_final=0
PRINT  'INFORME DE PEDIDOS DE EMPLEADO POR AÑO :'
-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR_EMPLE INTO @Y, @EMPLE, @NOMEMPLE, @IMPORTE
-- MIENTRA HAYA REGISTROS
WHILE @@FETCH_STATUS=0
BEGIN
   -- ASIGNAR A LA VARIABLE @Y1 EL VALOR INICIAL DE @Y
   SET @Y1 = @Y
   -- IMPRIMIR EL AÑO
   PRINT char(13) + 'AÑO:' + CAST(@Y1 AS VARCHAR)
   -- AQUIE VENDRA EN CADA INICIO DE AÑO, PONEMOS TOTAL A 0
   SET @TOTAL_año=0
-- nOS QUEDAMOS HASTA QUE CAMBIE EL AÑO O SEA FIN REGISTROS
   WHILE @Y1 = @Y AND @@FETCH_STATUS=0
   BEGIN
	--  ACUMULAR EL TOTAL
	SET @TOTAL_año += @IMPORTE
	-- IMPRIMIR EL REGISTRO
	PRINT CAST(@EMPLE AS VARCHAR) + SPACE(5)
		+CAST(@NOMEMPLE AS VARCHAR)+ SPACE(5)
		+STR(@IMPORTE)
	-- LEER EL REGISTRO SIGUIENTE
	FETCH MI_CURSOR_EMPLE INTO @Y, @EMPLE, @NOMEMPLE, @IMPORTE
   END
  --- TOTAL DE AÑO 
  PRINT char(13) +'IMPORTE EN:' +CAST(@Y1 AS VARCHAR) + SPACE(2)+ 'ES ' +CAST(@TOTAL_año AS VARCHAR)
  -- Acumulo total final
  SET @TOTAL_final += @TOTAL_año
END
-- IMPRIMIR LOS TOTALES FINALES
PRINT char(13) + 'IMPORTE TOTAL    '+STR(@TOTAL_final)
--FIN PROGRAMA
-- CERRAR
CLOSE MI_CURSOR_EMPLE
-- LIBERAR
DEALLOCATE MI_CURSOR_EMPLE;
