use negocios2011
DECLARE  @ART VARCHAR(20),@ART1 VARCHAR(20), @PEDIDO INT,@FECHA DATE,@IMPORTE DECIMAL,@TOTAL_ARTI
DECIMAL,@TOTALF DECIMAL
BEGIN
DECLARE MI_CURSOR_EJERCICIO_3 CURSOR FOR
SELECT P	,C.idpedido,C.fechapedido,
D.preciounidad*D.cantidad
FROM venta.PEDIDOSCABE C
JOIN  PEDIDOSDETA D ON C.IDPEDIDO=D.IDPEDIDO
JOIN COMPRAS .productos P ON D.idproducto=P.idproducto
where YEAR(FECHAPEDIDO)=2012
ORDER BY 1,2
OPEN MI_CURSOR_EJERCICIO_3
END
SET @TOTALF=0
PRINT'IMPORTE DE PEDIDOS DEL ARTICULO DEL AÑO 2012 '+ @art1 +':'
PRINT ''
FETCH MI_CURSOR_EJERCICIO_3 INTO @ART,@PEDIDO,@FECHA,@IMPORTE
WHILE @@FETCH_STATUS=0
BEGIN
	SET @TOTAL_ARTI=0
	SET @ART1=@ART
	PRINT'ARTICULO:'+@ART1 
	PRINT 'IDPEDIDO'+SPACE(10)+'FECHA'+SPACE(10)+'IMPORTE'
	WHILE @ART1=@ART AND @@FETCH_STATUS=0
	BEGIN
		SET @TOTAL_ARTI+=@IMPORTE
		PRINT SPACE(3)+CAST(@PEDIDO AS VARCHAR)+SPACE(10)+CAST(@FECHA AS VARCHAR)+SPACE(3)+STR(@IMPORTE)
		FETCH MI_CURSOR_EJERCICIO_3 INTO @ART,@PEDIDO,@FECHA,@IMPORTE
	END
	PRINT'TOTAL articulo:'+CAST(@ART1 AS VARCHAR)+SPACE(10)+CAST(@TOTAL_ARTI AS VARCHAR)
	PRINT ''
	SET @TOTALf+=@TOTAL_ARTI 
END
PRINT'IMPORTE TOTAL:'+SPACE(21)+CAST(@TOTALF AS VARCHAR)
PRINT ''
PRINT '_____________________________________________'
PRINT ''

CLOSE MI_CURSOR_EJERCICIO_3

DEALLOCATE MI_CURSOR_EJERCICIO_3;
