use negocios2011
DECLARE  @CAT VARCHAR(20),@CAT1 VARCHAR(20), @ART VARCHAR(20),@PRECIO DECIMAL, 
@PRECIOCAT DECIMAL, @NUMART INT, @PRECIOCATM DECIMAL, @PRECIOF DECIMAL, @NUMARTF INT, 
@PRECIOFM DECIMAL, @PRECIOFMC DECIMAL

DECLARE MI_CURSOR_EJERCICIO_4 CURSOR FOR
SELECT 
c.nombre_categoria ,
p.nombreproducto,
p.preciounidad
FROM  COMPRAS .productos p 
join dbo.categorias c ON c.idcategoria=p.idcategoria 
ORDER BY 1,2

OPEN MI_CURSOR_EJERCICIO_4

FETCH MI_CURSOR_EJERCICIO_4 INTO @CAT,@ART,@PRECIO
SET @PRECIOF=0
SET @NUMARTF=0
PRINT 'INFORME PRECIOS'
WHILE @@FETCH_STATUS=0
BEGIN
	SET @PRECIOCAT=0
	SET @NUMART=0
	SET @CAT1=@CAT
	PRINT'CATEGORIA:'+@CAT1 
	PRINT 'ARTICULO'+SPACE(10)+'PRECIO'
	WHILE(@CAT1=@CAT)AND @@FETCH_STATUS=0
	BEGIN
		SET @NUMART+=1
		SET @PRECIOCAT+=@PRECIO
		PRINT @ART+SPACE(8)+STR(@PRECIO)
		FETCH MI_CURSOR_EJERCICIO_4 INTO @CAT,@ART,@PRECIO
	END

SET @PRECIOCATM=@PRECIOCAT/@NUMART
PRINT'PRECIO MEDIO'+SPACE(8)+CAST(@PRECIOCATM AS VARCHAR)
PRINT ''
SET @PRECIOF+=@PRECIOCAT 
SET @NUMARTF+=@NUMART
END

SET @PRECIOFM=@PRECIOF/@NUMARTF
PRINT'PRECIO MEDIO FINAL (SUMA PRECIOS/Nº DE ARTICULOS):'+SPACE(3)+CAST(@PRECIOFM AS VARCHAR)
PRINT ''

CLOSE MI_CURSOR_EJERCICIO_4

DEALLOCATE MI_CURSOR_EJERCICIO_4
